builtin_interfaces/Time stamp

float64 kp
float64 kcte
float64 ki_cte
float64 kd
float64 look_ahead
float64 pivot_threshold
float64 cte_threshold
float64 cte_i_limit
float64 cte_i_active
float64 cte_i_decay
float64 wp_arrival_dist
float64 wp_skip_dist

float64 throttle_range
float64 pivot_range
float64 driver_mix
float64 pwm_center
float64 pwm_min
float64 pwm_max
float64 steering_reverse
float64 throttle_reverse
float64 left_motor_reverse
float64 right_motor_reverse

float64 k_rudder
float64 rudder_center
float64 rudder_min
float64 rudder_max
float64 rudder_reverse

float64 cmd_vel_speed
float64 cmd_vel_steer_scale
float64 cmd_vel_pivot_rate

float64 gnss_ofs_fwd
float64 gnss_ofs_left
float64 gnss_ofs_up
float64 gnss_ofs_yaw
