builtin_interfaces/Time stamp

float64 kp
float64 kcte
float64 ki
float64 kd
float64 look_ahead
float64 pivot_threshold
float64 cte_threshold
float64 wp_arrival_dist
float64 wp_skip_dist

float64 throttle_range
float64 pivot_range
float64 driver_mix
float64 pwm_center
float64 pwm_min
float64 pwm_max
float64 steering_reverse
float64 throttle_reverse

float64 k_rudder
float64 rudder_center
float64 rudder_min
float64 rudder_max
float64 rudder_reverse

float64 cmd_vel_speed
float64 cmd_vel_steer_scale
float64 cmd_vel_pivot_rate
